# video from midudev's youtube channel
  # https://www.youtube.com/watch?v=sIhm4YOMK6Q&list=WL&index=122&t=6181s
  # Github action  sonarcloud we used to do our workflows
  # https://github.com/marketplace/actions/sonarcloud-scan

name: CI/CD

on:
  push:
    branches-ignore:
      - main
      - develop

  pull_request_target:
    branches:
      - develop
      - main

jobs:
  sonarcloud:
    if: github.event.pull_request.base.ref != 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with: 
        args: >
          -Dsonar.organization=danieljacquin
          -Dsonar.projectKey=danieljacquin_todo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16.5.0'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run:  npm run build

  deploy:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20 
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

